import Ticket from '../models/Ticket.js';
import { triageIncomingTicket } from '../utils/geminiTriage.js';
import { addSlaJob } from '../queues/slaQueue.js';

export const createTicket = async (req, res) => {
  try {
    const { title, description, customerId } = req.body;

    if (!title || !description || !customerId) {
      return res.status(400).json({ message: 'Title, description, and customerId are required' });
    }

    // Call Gemini to analyze the description and return JSON categorization
    const aiClassification = await triageIncomingTicket(description);

    // Save the ticket in MongoDB
    const newTicket = await Ticket.create({
      title,
      description,
      customerId,
      status: 'Open',
      priority: aiClassification.priority || 'Low',
      tags: aiClassification.tags || [],
      // We are not passing category to the schema as we didn't add it in Phase 1, 
      // but we use the priority and tags generated by the AI
    });

    // Broadcast the new ticket to all connected agents
    const io = req.app.get('io');
    if (io) {
      io.to('agents').emit('ticket:created', newTicket);
    }

    // If it's a High priority ticket, add it to the SLA queue (30 seconds for testing)
    if (newTicket.priority === 'High') {
      await addSlaJob(newTicket._id, 30000);
    }

    res.status(201).json({
      message: 'Ticket created and triaged successfully',
      aiClassification, // Include this in the response so you can see what Gemini returned
      ticket: newTicket
    });
  } catch (error) {
    console.error('Error creating ticket:', error);
    res.status(500).json({ message: 'Internal Server Error' });
  }
};
